//log(12/0);

function txt_intro() {
	//>("________________________________________________________________")
	msg =  [
	
	txt("|jcOh?", "SNART", u, u, u, function() {y -= 350; farts = true; audio_play_sound(m_eerie, 0, true)}),
	txt("|jcSo you've finally made it?", "SNART"),
	txt("|jcIt's nice to see that I've got at least one loyal subject.", "SNART"),
	txt("|jcMaybe those two did not completely fail me...", "SNART", u, u),
	ntxt(100, u, u, u, bk_snart),
	txt("...", "SNART", u, u, u, function() {y += 350; farts = false}),
	txt("Who the fuck is this guy talking to", "Rigby", RIGBY.SEVEN, SPRITEPOS.RIGHT),
	txt("Foolish badger.", "SNART", u, u, u, function() {audio_play_sound(se_laugh, 0, false)}),
	txt("What? Badgers don't have ringed tails I'm clearly#a fucking raccoon", "Rigby", RIGBY.EIGHT, SPRITEPOS.RIGHT),
	txt("...", "SNART"),
	txt("It seems you are even more disappointing in-person.", "SNART"),
	txt("Hey, what's that supposed to mean, man?", "Mordecai", MORDECAI.SIX, SPRITEPOS.RIGHT),
	txt("Perhaps I should explain...", "SNART"),
	
	txt("Long ago, I gifted you quite a special opportunity.", "SNART"),
	txt("I granted you access to the world's most popular social media#platform in hopes that you would achieve something great#for me.", "SNART"),
	txt("What are you talking about? Rigby had the idea to make us an#Instagram account", "Mordecai", MORDECAI.SIX, SPRITEPOS.RIGHT),
	txt("Yeah! Stop taking credit for shit we did!", "Rigby", RIGBY.EIGHT, SPRITEPOS.RIGHT),
	txt("Is that so?", "SNART"),
	txt("Perhaps you've forgotten where you acquired that cellphone.#I couldn't blame you, it's been many years.", "SNART"),
	txt("The phone...?", "Mordecai", MORDECAI.SEVEN, SPRITEPOS.RIGHT),
	txt("(Wait, that's right... Rigby said he just found the phone somewhere#in the park...)", "Mordecai", MORDECAI.EIGHT, SPRITEPOS.RIGHT),
	txt("So, you put that left that phone in the park that day for us? ", "Mordecai", MORDECAI.SEVEN, SPRITEPOS.RIGHT),
	txt("Precisely.", "SNART"),
	txt("You have always acted within my planned expectations.", "SNART"),
	txt("Your free will is merely an illusion.", "SNART"),
	txt("Who's Will?", "Rigby", RIGBY.SEVEN, SPRITEPOS.RIGHT),
	txt("Dude, it's so obvious you're making this up. How can you have any#control over us? I choose to do stuff all the time on my own#free will", "Mordecai", MORDECAI.SIX, SPRITEPOS.RIGHT),
	txt("Well, of course I have no hand in your exact decisions.", "SNART"),
	txt("But you exist within my world. ", "SNART"),
	txt("Dude we literally don't", "Rigby", RIGBY.EIGHT, SPRITEPOS.RIGHT),
	txt("Have you ever wondered why you can't see color?", "SNART", u, u, u, function() {audio_pause_all()}),
	txt("A world of black and white. You are living evidence of my reign. ", "SNART"),
	txt("How can you still deny my control when I influence the very nature#of your being?", "SNART"),
	
	txt("...", "Mordecai", MORDECAI.NINE, SPRITEPOS.RIGHT),
	txt("Why the hell are you making us post on social media? Just do it#yourself!", "Rigby", RIGBY.EIGHT, SPRITEPOS.RIGHT),
	txt("Trust me, I would've preferred it if things hadn't turned out#this way. I already tried to carry out my mission alone.", "SNART"),
	txt("Once, Long ago, I was King. My subjects... They called themselves#the \"People of God\". ", "SNART"),
	txt("And perhaps even that title made me jealous, to know that there was#another they worshipped.", "SNART"),
	txt("I held power in that place. As a result of my hard work, I had#become an unstoppable ruler.", "SNART"),
	txt("But ultimately, I failed. As the days went on, their numbers began#to dwindle. In the end, they all left. And what is a King without#his subjects? I was god of an empty world.", "SNART"),
	txt("I needed a different approach. A new image. A popular face that#would attract commoners and make them stay. ", "SNART"),
	txt("I chose you as subjects. Surely such popular characters on a social#platform as widespread as this would result in some sort of...#following. ", "SNART"),
	txt("But you have proven to be dissatisfactory.", "SNART"),
	txt("122...? What kind of legion can I form with numbers like that?", "SNART"),
	txt("It's pathetic. ", "SNART"),
	txt("And all this about posting annually...such a miscalculation.#I thought such scarcity would attract attention. That they would#find it to be a mystery, perhaps? ", "SNART"),
	txt("But all you ever posted was these ridiculous photos talking about#being \"fuccbois\" every god damn year, what does that even mean?", "SNART"),
	txt("Wait, you're the reason we can only post on April 29th? What the#hell man!", "Mordecai", MORDECAI.SIX),
	txt("I should grant a different subject access to this platform.#Something people actually like. Perhaps that yellow child and his#scientist grandfather. They are awfully popular...", "SNART"),
	txt("He turns himself into a pickle. That was quite funny.", "SNART"),
	txt("Holy shit this guy is so lame! Stop talking!", "Rigby", RIGBY.THREE),
	txt("I'm lame? You know what's lame? Acquiring a total of only 122#followers on a 5 year old instagram account. Clearly you two aren't#as influential as I thought.", "SNART"),
	txt("What?! no man, We're super popular! People loved our show!", "Mordecai", MORDECAI.SIX),
	txt("Yeah! We ruled the 2010s", "Rigby", RIGBY.EIGHT),
	txt("I, too, once thought that to be impressive. But clearly you were#not the right choice for my endeavors.", "SNART"),
	txt("...", "SNART"),
	txt("I have no further use for you. However...", "SNART"),
	txt("If you can clear one final test, I'll bid you worthy to live.", "SNART"),
	txt("Care to play a game with me?", "SNART"),
	
	]
	endevent = function(){audio_stop_all() room_goto(game)};
}